# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:



frontend:
  themes: !include lovelace_configuration/themes.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include entities/groups.yaml
light: !include entities/lights/light.yaml
light groups: !include entities/lights/light-groups.yaml
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include_dir_merge_named scripts/
scene: !include entities/scenes.yaml
sensor: !include entities/sensors/sensors.yaml
binary_sensor: !include entities/sensors/binary_sensors.yaml
input_boolean: !include entities/inputs/input_booleans.yaml
input_number: !include entities/inputs/input_numbers.yaml
input_select: !include entities/inputs/input_selects.yaml
input_text: !include entities/inputs/input_texts.yaml
switch: !include entities/switches.yaml
template: !include entities/sensors/template.yaml
device_tracker: !include entities/trackers.yaml

lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml


wake_on_lan:

logger:
  default: warning
  logs:
    custom_components.ytube_music_player: debug
    custom_components.google_home: debug
    glocaltokens: debug

webostv:
  host: !secret webos_ip
  name: Living Room TV

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_subnet

google_assistant:
  project_id: !secret ghome_id
  service_account: !include google_service.json
  report_state: true
  expose_by_default: false
  exposed_domains:
    - switch
    - input_boolean
    - light
    - scene
  entity_config:
    light.bathroom_light:
      expose: true
    light.bedroom_spot_light:
      expose: true
    light.tall_light:
      expose: true
    light.bed_light:
      expose: true
    light.hallway_light:
      expose: true
    light.kitchen_spot_light_1:
      expose: true
    light.kitchen_spot_light_2:
      expose: true
    light.round_light:
      expose: true
    light.dining_table_light:
      expose: true
    light.window_light:
      expose: true
    input_boolean.start_goodnight:
      expose: true
    scene.bedroom_relax:
      expose: true
    scene.bedroom_bright:
      expose: true
    scene.bedroom_focus:
      expose: true
    scene.bedroom_night:
      expose: true
    scene.living_room_relax:
      expose: true
    scene.living_room_bright:
      expose: true
    scene.living_room_focus:
      expose: true
    scene.living_room_night:
      expose: true
    scene.hallway_relax:
      expose: true
    scene.hallway_bright:
      expose: true
    scene.hallway_focus:
      expose: true
    scene.kitchen_relax:
      expose: true
    scene.kitchen_bright:
      expose: true
    scene.kitchen_focus:
      expose: true

google:
  client_id: !secret g_uid
  client_secret: !secret g_secret

folder_watcher:
  - folder: /config/blueprints

homeassistant:
  allowlist_external_dirs:
    - "/config/blueprints"
  customize: !include customize.yaml




