- id: '59823490234'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_door_sensor_contact
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_off
      target:
        entity_id: light.bathroom_lights
    - wait_template: "{{ is_state('binary_sensor.hallway_sensor_contact', 'off') }}"
      timeout: "00:00:10"
    - service: input_boolean.turn_on
      target:
        entity_id: 
          - input_boolean.hallway_party
          - input_boolean.kitchen_party
          - input_boolean.living_room_party
    - service: tts.google_translate_say
      entity_id: media_player.bathroom_speaker
      data_template:
         message: "Welcome back Solveig, to the superior scandinavian country. We hope you enjoyed your little getaway."
    - delay: 20
    - service: input_boolean.turn_off
      target:
        entity_id: 
          - input_boolean.hallway_party
          - input_boolean.kitchen_party
          - input_boolean.living_room_party
    - service: scene.turn_on
      target: 
        entity_id: 
          - scene.kitchen_bright
          - scene.hallway_evening
          - scene.living_room_bright
- alias: 'Set theme at startup'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: mobile
- id: '12389052034234'
  alias: Keep Bedroom Speaker Alive
  trigger:
    platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.bedroom_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.bedroom_speaker
        state: 'idle'
      - condition: state
        entity_id: media_player.bedroom_speaker
        state: 'paused'
        for: '15:00'
  action:
    - service: script.bedroom_keep_alive
- id: '12093458094355'
  alias: Keep Living Room Speaker Alive
  trigger:
    platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.living_room_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.living_room_speaker
        state: 'idle'
      - condition: state
        entity_id: media_player.living_room_speaker
        state: 'paused'
        for: '15:00'
  action:
    - service: script.living_room_keep_alive

- id: '3459034590345'
  alias: Keep Bathroom Speaker Alive
  trigger:
    platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.bathroom_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.bathroom_speaker
        state: 'idle'
      - condition: state
        entity_id: media_player.bathroom_speaker
        state: 'paused'
        for: '15:00'
  action:
    - service: script.bathroom_keep_alive

- id: '24234902345'
  alias: Keep Kitchen Speaker Alive
  trigger:
    platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.kitchen_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.kitchen_speaker
        state: 'idle'
      - condition: state
        entity_id: media_player.kitchen_speaker
        state: 'paused'
        for: '15:00'
  action:
    - service: script.kitchen_keep_alive

